"""
Hand-curated mathematical type annotations for LMFDB database columns.

Keys are "table_name.column_name", values are concise mathematical type descriptions
derived from reading web_*.py, main.py, verify/*.py, and import scripts.

Convention for descriptions:
  - Start with the mathematical object
  - Then describe the encoding if non-obvious
  - Use examples for complex structures
"""

# fmt: off
MATH_TYPES = {
    # =========================================================================
    # ec_curvedata — Elliptic curves over Q
    # =========================================================================
    "ec_curvedata.lmfdb_label": "LMFDB label: N.c.n (conductor.isogeny_class.curve_number), e.g. '11.a1'",
    "ec_curvedata.lmfdb_iso": "isogeny class label: N.c, e.g. '11.a'",
    "ec_curvedata.lmfdb_number": "1-indexed position within isogeny class (LMFDB ordering)",
    "ec_curvedata.Clabel": "Cremona label, e.g. '11a1'",
    "ec_curvedata.Ciso": "Cremona isogeny class label, e.g. '11a'",
    "ec_curvedata.Cnumber": "1-indexed position in isogeny class (Cremona ordering)",
    "ec_curvedata.conductor": "positive integer, conductor of the curve",
    "ec_curvedata.ainvs": "Weierstrass a-invariants [a1,a2,a3,a4,a6] as numeric[5]. Defines y^2+a1*xy+a3*y = x^3+a2*x^2+a4*x+a6",
    "ec_curvedata.jinv": "j-invariant as numeric[2]: [numerator, denominator]. Reconstruct via QQ(tuple(jinv))",
    "ec_curvedata.signD": "+1 or -1, sign of minimal discriminant",
    "ec_curvedata.absD": "absolute value of minimal discriminant, arbitrary-precision",
    "ec_curvedata.rank": "non-negative integer, Mordell-Weil rank",
    "ec_curvedata.torsion": "positive integer, order of torsion subgroup E(Q)_tors",
    "ec_curvedata.torsion_structure": "invariant factors of E(Q)_tors in ascending order, e.g. [2,4] means Z/2 x Z/4. Empty [] for trivial",
    "ec_curvedata.analytic_rank": "non-negative integer, order of vanishing of L(E,s) at s=1",
    "ec_curvedata.sha": "positive integer, analytic order of Sha (Tate-Shafarevich group), rounded",
    "ec_curvedata.regulator": "positive real (arbitrary-precision), regulator of Mordell-Weil group",
    "ec_curvedata.faltings_height": "real (arbitrary-precision), Faltings height",
    "ec_curvedata.stable_faltings_height": "real (arbitrary-precision), stable Faltings height (isogeny-invariant)",
    "ec_curvedata.degree": "positive integer, degree of modular parametrization X_0(N) -> E",
    "ec_curvedata.cm": "CM discriminant (negative integer) or 0 if no CM. E.g. -3, -4, -7, ..., 0",
    "ec_curvedata.bad_primes": "sorted list of primes of bad reduction",
    "ec_curvedata.num_bad_primes": "count of primes of bad reduction",
    "ec_curvedata.nonmax_primes": "primes ell where mod-ell Galois image is not maximal in GL2(F_ell)",
    "ec_curvedata.nonmax_rad": "product of nonmax_primes",
    "ec_curvedata.elladic_images": "Sutherland labels of ell-adic Galois images in GL2(Z_ell), format 'ell.index.surjdet.label'",
    "ec_curvedata.modell_images": "Sutherland labels of mod-ell Galois images in GL2(F_ell)",
    "ec_curvedata.modm_images": "RSZB labels of mod-m Galois images, format 'N.M.d.label'",
    "ec_curvedata.adelic_level": "positive integer, level M of adelic image (largest level of a modular curve with rational point)",
    "ec_curvedata.adelic_index": "positive integer, index [GL2(Z-hat) : rho_E(Gal)]",
    "ec_curvedata.adelic_genus": "non-negative integer, genus of the modular curve X_H where H = rho_E(Gal)",
    "ec_curvedata.isogeny_degrees": "sorted list of degrees of cyclic isogenies from this curve, e.g. [1, 5, 25]",
    "ec_curvedata.class_size": "positive integer, number of curves in the isogeny class",
    "ec_curvedata.class_deg": "positive integer, LCM of isogeny degrees in the class",
    "ec_curvedata.semistable": "boolean, true if all bad reduction is multiplicative",
    "ec_curvedata.potential_good_reduction": "boolean, true if E has potential good reduction at all primes",
    "ec_curvedata.squarefree_disc": "boolean, true if discriminant is squarefree",
    "ec_curvedata.min_quad_twist_disc": "discriminant d of the quadratic twist E_d that is minimal",
    "ec_curvedata.min_quad_twist_ainvs": "a-invariants of minimal quadratic twist, same format as ainvs",
    "ec_curvedata.manin_constant": "positive integer, Manin constant c_E",
    "ec_curvedata.optimality": "0 = not optimal, 1 = optimal (Gamma_0(N)-optimal), n>1 = n candidates",
    "ec_curvedata.sha_primes": "prime divisors of the analytic order of Sha",
    "ec_curvedata.torsion_primes": "prime divisors of torsion order",
    "ec_curvedata.serre_invariants": "flat triples [p1,w1,n1, p2,w2,n2,...]: prime, Serre weight, conductor exponent",
    "ec_curvedata.num_int_pts": "non-negative integer, count of integral points on minimal model",
    "ec_curvedata.intrinsic_torsion": "positive integer, order of intrinsic torsion subgroup",
    "ec_curvedata.abc_quality": "floating-point, quality q(a,b,c) of the abc-triple for the j-invariant",
    "ec_curvedata.szpiro_ratio": "floating-point, Szpiro ratio log|Delta|/log(N)",
    "ec_curvedata.faltings_index": "1-indexed position in isogeny class sorted by Faltings height",
    "ec_curvedata.faltings_ratio": "integer ratio of period area to that of minimal-Faltings-height curve in class",
    "ec_curvedata.iso_nlabel": "numerical encoding of isogeny class letter (a=0, b=1, ...)",

    # =========================================================================
    # ec_classdata — Isogeny class data (modular form side)
    # =========================================================================
    "ec_classdata.lmfdb_iso": "isogeny class label, e.g. '11.a'",
    "ec_classdata.conductor": "positive integer",
    "ec_classdata.class_size": "positive integer, number of curves in class",
    "ec_classdata.class_deg": "positive integer, LCM of isogeny degrees",
    "ec_classdata.anlist": "L-series coefficients a_n for n=0..19. a_0=0, a_1=1, then a_2,...,a_19",
    "ec_classdata.aplist": "traces of Frobenius a_p for first 25 primes (p=2,3,5,...,97). Index 0 = a_2",
    "ec_classdata.isogeny_matrix": "flattened row-major N x N matrix of cyclic isogeny degrees. For class_size=N, has N^2 entries. Symmetric. M[i][j] = degree of cyclic isogeny from curve i to curve j (LMFDB ordering)",
    "ec_classdata.trace_hash": "64-bit hash of Frobenius traces for fast isogeny class lookup",

    # =========================================================================
    # ec_mwbsd — Mordell-Weil and BSD data
    # =========================================================================
    "ec_mwbsd.lmfdb_label": "curve label",
    "ec_mwbsd.conductor": "positive integer",
    "ec_mwbsd.ngens": "non-negative integer, number of stored free generators (= rank)",
    "ec_mwbsd.gens": "free generators in weighted projective coords, flat: [a1,b1,c1, a2,b2,c2,...]. Point = (a/c^2, b/c^3)",
    "ec_mwbsd.heights": "Neron-Tate canonical heights of generators, arbitrary-precision reals",
    "ec_mwbsd.torsion_generators": "torsion generators in weighted projective coords [a,b,c], flat like gens",
    "ec_mwbsd.xcoord_integral_points": "x-coordinates of integral points on minimal model",
    "ec_mwbsd.real_period": "positive real (arbitrary-precision), real period Omega_E",
    "ec_mwbsd.special_value": "L^(r)(E,1)/r! where r = analytic rank, arbitrary-precision",
    "ec_mwbsd.sha_an": "analytic order of Sha from BSD formula, arbitrary-precision",
    "ec_mwbsd.tamagawa_product": "positive integer, product of local Tamagawa numbers prod_p c_p",
    "ec_mwbsd.area": "covolume of period lattice, arbitrary-precision positive real",
    "ec_mwbsd.rank_bounds": "[lower, upper] bounds for rank when exact rank unknown",

    # =========================================================================
    # ec_localdata — Local reduction data at each bad prime
    # =========================================================================
    "ec_localdata.lmfdb_label": "curve label",
    "ec_localdata.conductor": "positive integer",
    "ec_localdata.prime": "prime p of bad reduction",
    "ec_localdata.reduction_type": "-1 = nonsplit multiplicative, 0 = additive, +1 = split multiplicative",
    "ec_localdata.conductor_valuation": "v_p(N), exponent of p in conductor",
    "ec_localdata.discriminant_valuation": "v_p(Delta), exponent of p in discriminant",
    "ec_localdata.kodaira_symbol": "PARI encoding: 1..10 = I_0..I_10; -1 = I*_0; <= -14: I*_m where m = -(code+4)",
    "ec_localdata.tamagawa_number": "positive integer c_p, local Tamagawa number at p",
    "ec_localdata.root_number": "local root number epsilon_p in {0, 1}",
    "ec_localdata.j_denominator_valuation": "v_p(denominator of j-invariant)",

    # =========================================================================
    # ec_galrep — Galois representation data
    # =========================================================================
    "ec_galrep.lmfdb_label": "curve label",
    "ec_galrep.conductor": "positive integer",
    "ec_galrep.prime": "prime ell for ell-adic data; 0 = adelic data",
    "ec_galrep.elladic_image": "Sutherland label of ell-adic image in GL2(Z_ell)",
    "ec_galrep.modell_image": "Sutherland label of mod-ell image in GL2(F_ell)",
    "ec_galrep.adelic_image": "RSZB label of adelic image in GL2(Z-hat), only for prime=0",
    "ec_galrep.adelic_gens": "generating matrices as flat 4-tuples [a,b,c,d, a,b,c,d,...] for 2x2 matrices mod M",

    # =========================================================================
    # ec_iwasawa — Iwasawa invariants
    # =========================================================================
    "ec_iwasawa.lmfdb_label": "curve label",
    "ec_iwasawa.conductor": "positive integer",
    "ec_iwasawa.iwp0": "smallest prime p0 such that lambda=mu=0 for all good primes p >= p0. NULL if unknown",
    "ec_iwasawa.iwdata": "JSON object: keys = prime strings, values = [lambda,mu] (ordinary) or [lambda0,lambda1,mu] (supersingular) or 'o?'/'ss?' (unknown)",

    # =========================================================================
    # ec_padic — p-adic regulator data
    # =========================================================================
    "ec_padic.lmfdb_iso": "isogeny class label",
    "ec_padic.p": "prime p",
    "ec_padic.val": "p-adic valuation v_p(R_p) of p-adic regulator",
    "ec_padic.unit": "unit part of p-adic regulator (coprime to p), arbitrary-precision",
    "ec_padic.prec": "p-adic precision of computation",

    # =========================================================================
    # ec_sympow — Symmetric power L-function data
    # =========================================================================
    "ec_sympow.lmfdb_iso": "isogeny class label",
    "ec_sympow.power": "positive integer k, the symmetric power Sym^k",
    "ec_sympow.conductor": "conductor of Sym^k(E), arbitrary-precision",

    # =========================================================================
    # ec_torsion_growth — Torsion growth in extensions
    # =========================================================================
    "ec_torsion_growth.lmfdb_label": "curve label over Q",
    "ec_torsion_growth.conductor": "positive integer",
    "ec_torsion_growth.degree": "degree [K:Q] of extension field",
    "ec_torsion_growth.field": "defining polynomial coefficients [a0,a1,...,an] of K/Q (constant term first)",
    "ec_torsion_growth.torsion": "torsion structure of E(K)_tors, invariant factors e.g. [2,8]",

    # =========================================================================
    # ec_nfcurves — Elliptic curves over number fields
    # =========================================================================
    "ec_nfcurves.label": "full label: field-cond_norm-cond_label-class-number, e.g. '2.0.4.1-100.1-a1'",
    "ec_nfcurves.field_label": "number field label d.r1.disc.index, e.g. '2.0.4.1'",
    "ec_nfcurves.degree": "degree [K:Q]",
    "ec_nfcurves.conductor_norm": "positive integer, norm N(conductor ideal)",
    "ec_nfcurves.conductor_label": "label of conductor ideal, e.g. '100.1'",
    "ec_nfcurves.conductor_ideal": "human-readable ideal representation",
    "ec_nfcurves.iso_label": "short isogeny class label (without field prefix)",
    "ec_nfcurves.iso_nlabel": "numerical isogeny class index (a=0, b=1, ...)",
    "ec_nfcurves.number": "1-indexed curve number in isogeny class",
    "ec_nfcurves.ainvs": "text: 5 a-invariants as semicolon-separated field elements. Each element = comma-separated coefficients in power basis {1,alpha,alpha^2,...}. E.g. '0,0;-1,0;1,0;0,-1;0,-1'",
    "ec_nfcurves.jinv": "j-invariant as text string (exact field element representation)",
    "ec_nfcurves.disc": "discriminant as text (ideal or integer)",
    "ec_nfcurves.abs_disc": "|N(discriminant ideal)|",
    "ec_nfcurves.normdisc": "norm of minimal discriminant ideal, arbitrary-precision",
    "ec_nfcurves.class_size": "positive integer, curves in isogeny class",
    "ec_nfcurves.class_deg": "positive integer, LCM of isogeny degrees",
    "ec_nfcurves.rank": "non-negative integer, Mordell-Weil rank over K",
    "ec_nfcurves.rank_bounds": "JSON [lower, upper] bounds for Mordell-Weil rank, e.g. [0, 2] means 0 <= rank <= 2",
    "ec_nfcurves.analytic_rank": "non-negative integer",
    "ec_nfcurves.torsion_order": "positive integer, |E(K)_tors|",
    "ec_nfcurves.torsion_structure": "JSON list of invariant factors of E(K)_tors ascending, e.g. [2,4] = Z/2 x Z/4. Empty [] for trivial",
    "ec_nfcurves.torsion_gens": "JSON list of strings, each a torsion generator as projective point '[[c0,...],[d0,...],[e0,...]]' where each coord is coeffs in power basis of K/Q",
    "ec_nfcurves.torsion_primes": "prime divisors of torsion order",
    "ec_nfcurves.ngens": "number of stored Mordell-Weil generators",
    "ec_nfcurves.gens": "JSON list of strings, each a MW generator as projective point '[[c0,...],[d0,...],[e0,...]]' where each coord is rational coeffs in {1,alpha,...} basis. Affine point = (x,y) with x=a/c^2, y=b/c^3",
    "ec_nfcurves.heights": "Neron-Tate heights of generators",
    "ec_nfcurves.sha": "analytic order of Sha",
    "ec_nfcurves.reg": "regulator, arbitrary-precision",
    "ec_nfcurves.omega": "period (product of local periods), arbitrary-precision",
    "ec_nfcurves.Lvalue": "L(E,1) or L^(r)(E,1)/r!, arbitrary-precision",
    "ec_nfcurves.tamagawa_product": "positive integer, product of Tamagawa numbers",
    "ec_nfcurves.cm": "CM discriminant or 0",
    "ec_nfcurves.cm_type": "0 = no CM, 1 = potential CM, 2 = actual CM over K",
    "ec_nfcurves.q_curve": "boolean, true if E is isogenous to all its Galois conjugates",
    "ec_nfcurves.semistable": "boolean",
    "ec_nfcurves.potential_good_reduction": "boolean",
    "ec_nfcurves.nonmax_primes": "primes with non-maximal mod-p Galois image",
    "ec_nfcurves.nonmax_rad": "product of nonmax_primes",
    "ec_nfcurves.reducible_primes": "primes with reducible mod-p Galois representation",
    "ec_nfcurves.local_data": "JSON list of dicts per bad prime: keys {p (ideal string in w-notation), normp (int), ord_cond, ord_disc, ord_den_j, cp (Tamagawa number), kod (PARI Kodaira symbol int), red (0=additive, 1=split mult, -1=nonsplit mult), rootno (local root number)}",
    "ec_nfcurves.isodeg": "degrees of cyclic isogenies from this curve",
    "ec_nfcurves.isogeny_matrix": "JSON nested list [[d_ij,...],...] of isogeny degrees: M[i][j] = degree of cyclic isogeny from curve i to j. Symmetric, diagonal = 1",
    "ec_nfcurves.galois_images": "JSON list of Sutherland GL2(F_p) subgroup labels for non-maximal images, parallel to nonmax_primes. E.g. ['2B', '3Cs.1.1']",
    "ec_nfcurves.base_change": "JSON list of curve labels this is a base change of. Labels without '-' = curves over Q (Cremona labels), with '-' = curves over number fields (ECNF labels). Empty [] = not a base change",
    "ec_nfcurves.signature": "JSON [r1, r2]: r1 = real embeddings, r2 = complex pairs. r1+2*r2 = [K:Q]",
    "ec_nfcurves.bad_primes": "JSON list of prime ideal strings in w-generator notation, e.g. ['(2,w+1)', '(3)']",
    "ec_nfcurves.non_min_p": "JSON list of prime ideal strings where the stored model is not minimal. Usually [] (globally minimal) or length 1",
    "ec_nfcurves.equation": "Weierstrass equation as LaTeX string",
    "ec_nfcurves.root_analytic_conductor": "floating-point, root analytic conductor",
    "ec_nfcurves.trace_hash": "64-bit hash of traces for fast lookup",

    # ===== ec_nfportraits =====
    "ec_nfportraits.label": "curve label",
    "ec_nfportraits.portrait": "base64-encoded PNG image of curve portrait",

    # ===== ec_iqf_labels =====
    "ec_iqf_labels.fld": "imaginary quadratic field label",
    "ec_iqf_labels.old": "old-style ideal label",
    "ec_iqf_labels.new": "standard ideal label",

    # =========================================================================
    # mf_newforms — Classical modular newforms
    # =========================================================================
    "mf_newforms.label": "label N.k.a.x: level.weight.char_orbit.hecke_orbit, e.g. '1.12.a.a'",
    "mf_newforms.level": "positive integer N (level of Gamma_0(N))",
    "mf_newforms.weight": "positive integer k (weight of modular form)",
    "mf_newforms.char_orbit_index": "1-indexed ordinal of Galois orbit of Dirichlet character",
    "mf_newforms.char_orbit_label": "base-26 encoded character orbit (a=1, b=2, ...)",
    "mf_newforms.hecke_orbit": "index of Hecke orbit within the newspace",
    "mf_newforms.hecke_orbit_code": "64-bit packed int: N + (k<<24) + ((char_orbit_index-1)<<36) + ((hecke_orbit-1)<<52)",
    "mf_newforms.dim": "non-negative integer, absolute dimension [Q(f):Q]",
    "mf_newforms.relative_dim": "dimension over character field, dim / char_degree",
    "mf_newforms.space_label": "parent newspace label N.k.a",
    "mf_newforms.traces": "integer trace values tr(a_n) for n=1 to ~1000, arbitrary-precision",
    "mf_newforms.trace_display": "first four traces [tr(a_2), tr(a_3), tr(a_5), tr(a_7)]",
    "mf_newforms.trace_hash": "64-bit hash for fast trace-based lookup",
    "mf_newforms.analytic_conductor": "floating-point, analytic conductor",
    "mf_newforms.field_poly": "coefficients of defining polynomial of Hecke field Q(f), Sage ordering (high degree first). E.g. [1,0,-5,0,1] for x^4-5x^2+1",
    "mf_newforms.field_disc": "discriminant of Hecke field Q(f), arbitrary-precision",
    "mf_newforms.field_disc_factorization": "factorization as flat list [p1,e1, p2,e2,...] of (prime, exponent) pairs",
    "mf_newforms.field_poly_root_of_unity": "m if Q(f) = Q(zeta_m) or Q(zeta_m)+, else NULL",
    "mf_newforms.field_poly_is_cyclotomic": "boolean",
    "mf_newforms.field_poly_is_real_cyclotomic": "boolean",
    "mf_newforms.nf_label": "LMFDB number field label (only for dim <= 20)",
    "mf_newforms.conrey_index": "Conrey label n of first character in the Galois orbit",
    "mf_newforms.char_values": "JSON: [[m1,[a11,...,a1d]], [m2,[a21,...,a2d]], ...] character values on generators of (Z/NZ)*. Each value is an element of Q(zeta_n) expressed as integer vector in power basis",
    "mf_newforms.char_conductor": "conductor of the character chi",
    "mf_newforms.char_order": "multiplicative order of chi",
    "mf_newforms.char_degree": "degree [Q(chi):Q]",
    "mf_newforms.char_parity": "1 = even, -1 = odd",
    "mf_newforms.char_is_real": "boolean, true if chi is real-valued (trivial or quadratic)",
    "mf_newforms.self_twist_discs": "list of discriminants d for self-twists chi_d. CM: d<0. RM: d>0. Empty if no self-twist",
    "mf_newforms.cm_discs": "negative discriminants from self_twist_discs (CM twists)",
    "mf_newforms.rm_discs": "positive discriminants from self_twist_discs (RM twists)",
    "mf_newforms.is_cm": "boolean",
    "mf_newforms.is_rm": "boolean",
    "mf_newforms.is_self_twist": "boolean",
    "mf_newforms.self_twist_type": "0=none, 1=CM, 2=RM, 3=both",
    "mf_newforms.is_self_dual": "boolean, true if coefficient field is totally real",
    "mf_newforms.inner_twist_count": "number of inner twists, -1 if unknown",
    "mf_newforms.analytic_rank": "non-negative integer, order of vanishing of L(f,s) at center",
    "mf_newforms.analytic_rank_proved": "boolean",
    "mf_newforms.is_twist_minimal": "boolean, true if this is the twist-minimal form",
    "mf_newforms.minimal_twist": "label of the twist-minimal form in the twist class",
    "mf_newforms.hecke_ring_index": "index [O_max : O_Hecke] of Hecke order in maximal order, arbitrary-precision",
    "mf_newforms.hecke_ring_index_factorization": "factorization as flat [p1,e1, p2,e2,...]",
    "mf_newforms.hecke_ring_index_proved": "boolean",
    "mf_newforms.hecke_ring_generator_nbound": "minimal m such that a_1,...,a_m generate the Hecke ring",
    "mf_newforms.atkin_lehner_eigenvals": "JSON list of [p, eigenvalue] pairs: [[p1,+/-1], [p2,+/-1],...] for primes p | N",
    "mf_newforms.atkin_lehner_string": "string of +/- chars for quick search, e.g. '+-+'",
    "mf_newforms.fricke_eigenval": "product of all Atkin-Lehner eigenvalues, +1 or -1 (trivial char only)",
    "mf_newforms.projective_image": "label of projective image: Dn, A4, S4, A5 (weight 1 only)",
    "mf_newforms.projective_image_type": "type name: 'Dn', 'A4', 'S4', 'A5' (weight 1 only)",
    "mf_newforms.is_polredabs": "boolean, true if field_poly is polredabs-reduced",
    "mf_newforms.Nk2": "N * k^2 (used for ordering and search)",
    "mf_newforms.qexp_display": "LaTeX string of q-expansion for display",
    "mf_newforms.related_objects": "list of URL strings to related LMFDB objects",
    "mf_newforms.embedded_related_objects": "list of URL strings indexed by embedding_m",

    # =========================================================================
    # mf_newspaces — Spaces of newforms S_k^new(N, chi)
    # =========================================================================
    "mf_newspaces.label": "label N.k.a: level.weight.char_orbit",
    "mf_newspaces.level": "positive integer N",
    "mf_newspaces.weight": "positive integer k",
    "mf_newspaces.char_orbit_index": "1-indexed ordinal of character orbit",
    "mf_newspaces.char_orbit_label": "base-26 label (a=1, b=2, ...)",
    "mf_newspaces.conrey_index": "Conrey label of first character in orbit",
    "mf_newspaces.char_order": "multiplicative order of chi",
    "mf_newspaces.char_degree": "[Q(chi):Q]",
    "mf_newspaces.char_conductor": "conductor of chi",
    "mf_newspaces.char_parity": "1 = even, -1 = odd",
    "mf_newspaces.char_is_real": "boolean",
    "mf_newspaces.dim": "Q-dimension of S_k^new(N,chi)",
    "mf_newspaces.cusp_dim": "Q-dimension of full cuspidal space S_k(N,chi)",
    "mf_newspaces.eis_dim": "Q-dimension of Eisenstein subspace of M_k(N,chi)",
    "mf_newspaces.eis_new_dim": "Q-dimension of new Eisenstein part",
    "mf_newspaces.mf_dim": "Q-dimension of M_k(N,chi)",
    "mf_newspaces.mf_new_dim": "Q-dimension of M_k^new(N,chi)",
    "mf_newspaces.num_forms": "count of Hecke orbits (newforms) in this space",
    "mf_newspaces.hecke_orbit_dims": "sorted list of dimensions of Hecke orbits, ascending",
    "mf_newspaces.traces": "integer trace form coefficients tr(a_n) for n=1 to ~1000",
    "mf_newspaces.trace_display": "[tr(a_2), tr(a_3), tr(a_5), tr(a_7)]",
    "mf_newspaces.trace_bound": "minimal n such that tr(a_1),...,tr(a_n) distinguish all forms in the space",
    "mf_newspaces.ALdims": "Atkin-Lehner eigenspace dimensions (trivial char only). List indexed by subsets of bad primes",
    "mf_newspaces.plus_dim": "dimension of Fricke eigenvalue +1 subspace (trivial char only)",
    "mf_newspaces.level_primes": "prime divisors of N, sorted",
    "mf_newspaces.level_radical": "product of prime divisors of N (radical)",
    "mf_newspaces.sturm_bound": "floor(k * [SL2(Z):Gamma0(N)] / 12)",
    "mf_newspaces.Nk2": "N * k^2",
    "mf_newspaces.analytic_conductor": "analytic conductor N * (psi(k/2) / (2*pi))^2, floating-point",
    "mf_newspaces.relative_dim": "dim / char_degree",
    "mf_newspaces.hecke_orbit_code": "64-bit encoding N + (k<<24) + ((char_orbit_index-1)<<36)",

    # =========================================================================
    # mf_hecke_nf — Exact Hecke eigenvalues in number fields (dim <= 20)
    # =========================================================================
    "mf_hecke_nf.label": "newform label N.k.a.x",
    "mf_hecke_nf.hecke_orbit_code": "64-bit encoding (same as mf_newforms)",
    "mf_hecke_nf.field_poly": "defining polynomial of Hecke field, coefficient ordering matches Sage (high degree first)",
    "mf_hecke_nf.hecke_ring_rank": "dim(newform) = degree of field_poly",
    "mf_hecke_nf.hecke_ring_power_basis": "boolean, true if using {1, alpha, alpha^2, ...} basis",
    "mf_hecke_nf.hecke_ring_cyclotomic_generator": "m if field is Q(zeta_m) and using cyclotomic basis; 0 otherwise",
    "mf_hecke_nf.hecke_ring_numerators": "basis change matrix numerators: list of integer lists, each row = basis element as linear combination of power basis. Flattened for storage",
    "mf_hecke_nf.hecke_ring_denominators": "denominators corresponding to hecke_ring_numerators entries",
    "mf_hecke_nf.hecke_ring_inverse_numerators": "inverse basis change matrix numerators",
    "mf_hecke_nf.hecke_ring_inverse_denominators": "inverse basis change denominators",
    "mf_hecke_nf.hecke_ring_character_values": "JSON [[g1,[a11,...,a1d]],[g2,...]] character values on generators of (Z/NZ)*",
    "mf_hecke_nf.an": "JSON: first 100 eigenvalues. If cyclotomic_generator=0: each a_n = [c0,...,cd-1] in Hecke ring basis. If cyclotomic_generator=m: each a_n = [[c1,e1],...,[ck,ek]] sparse polynomial in zeta_m",
    "mf_hecke_nf.ap": "JSON: eigenvalues a_p for primes p up to maxp, same format as an",
    "mf_hecke_nf.maxp": "largest prime for which a_p is stored",

    # =========================================================================
    # mf_hecke_cc — Complex Hecke eigenvalues (all forms, embedded)
    # =========================================================================
    "mf_hecke_cc.label": "embedded label N.k.a.x.n.i (includes Conrey index and embedding index)",
    "mf_hecke_cc.hecke_orbit_code": "64-bit encoding",
    "mf_hecke_cc.conrey_index": "Conrey label of the character used for this embedding",
    "mf_hecke_cc.dual_conrey_index": "Conrey label of complex conjugate character",
    "mf_hecke_cc.embedding_m": "global index among all embeddings of this newform",
    "mf_hecke_cc.embedding_index": "index among embeddings with same conrey_index",
    "mf_hecke_cc.embedding_root_real": "real part of the root defining this embedding",
    "mf_hecke_cc.embedding_root_imag": "imaginary part of the root defining this embedding",
    "mf_hecke_cc.an_normalized": "double precision[]: flat pairs [x1,y1, x2,y2,...] where a_n = n^((k-1)/2) * (x_n + i*y_n)",
    "mf_hecke_cc.angles": "double precision[]: Sato-Tate angles theta_p. a_p = 2*p^((k-1)/2)*cos(2*pi*theta_p) for good primes; NULL for bad primes",

    # ===== mf_hecke_traces =====
    "mf_hecke_traces.hecke_orbit_code": "64-bit encoding",
    "mf_hecke_traces.n": "index n of the eigenvalue a_n",
    "mf_hecke_traces.trace_an": "tr(a_n) as arbitrary-precision integer",

    # ===== mf_hecke_charpolys =====
    "mf_hecke_charpolys.hecke_orbit_code": "64-bit encoding",
    "mf_hecke_charpolys.p": "prime p",
    "mf_hecke_charpolys.charpoly_factorization": "JSON: [[coeffs1, e1], [coeffs2, e2], ...] factored characteristic polynomial det(T-a_p). Each coeffs is polynomial coefficients (constant first)",

    # ===== mf_hecke_lpolys =====
    "mf_hecke_lpolys.hecke_orbit_code": "64-bit encoding",
    "mf_hecke_lpolys.p": "prime p",
    "mf_hecke_lpolys.lpoly": "L-polynomial coefficients at p (constant term first)",
    "mf_hecke_lpolys.lpoly_factorization": "JSON: factorization of L-polynomial over Q",

    # ===== mf_twists_nf =====
    "mf_twists_nf.source_label": "source newform label",
    "mf_twists_nf.target_label": "twisted newform label",
    "mf_twists_nf.twist_class_label": "label of twist-minimal representative",
    "mf_twists_nf.twisting_char_label": "character orbit label of the twisting character",
    "mf_twists_nf.multiplicity": "count of distinct twists by same character orbit",

    # ===== mf portraits =====
    "mf_newform_portraits.label": "newform label",
    "mf_newform_portraits.portrait": "base64-encoded PNG image",
    "mf_newspace_portraits.label": "newspace label",
    "mf_newspace_portraits.portrait": "base64-encoded PNG image",

    # =========================================================================
    # nf_fields — Number fields
    # =========================================================================
    "nf_fields.label": "label d.r.D.i: degree.r2.abs_disc.index, e.g. '2.2.5.1'",
    "nf_fields.degree": "degree [K:Q]",
    "nf_fields.coeffs": "polynomial coefficients of defining polredabs polynomial. Sage ordering: [a_n, a_{n-1}, ..., a_1, a_0] (leading coeff first)",
    "nf_fields.disc_sign": "+1 or -1, sign of discriminant",
    "nf_fields.disc_abs": "absolute value of discriminant |D_K|",
    "nf_fields.r2": "number of pairs of complex embeddings: r2 = (deg - r1)/2",
    "nf_fields.galois_label": "transitive group label nTt, e.g. '5T3'",
    "nf_fields.ramps": "primes dividing discriminant (ramified primes), sorted",
    "nf_fields.class_number": "class number h(K)",
    "nf_fields.narrow_class_number": "narrow class number h+(K)",
    "nf_fields.class_group": "invariant factors of class group as text, e.g. '[2,4]' or '[]'",
    "nf_fields.regulator": "regulator R(K), floating-point",
    "nf_fields.rd": "root discriminant |D|^(1/d)",
    "nf_fields.grd": "Galois root discriminant |D_K|^(1/|Gal|)",
    "nf_fields.used_grh": "boolean, true if computations assume GRH",
    "nf_fields.cm": "boolean, true if K is a CM field",
    "nf_fields.is_galois": "boolean, true if K/Q is Galois",
    "nf_fields.gal_is_cyclic": "boolean",
    "nf_fields.gal_is_abelian": "boolean",
    "nf_fields.gal_is_solvable": "boolean",
    "nf_fields.monogenic": "boolean or null: true if O_K = Z[alpha] for some alpha",
    "nf_fields.num_ram": "count of ramified primes",

    # =========================================================================
    # g2c_curves — Genus 2 curves over Q
    # =========================================================================
    "g2c_curves.label": "label: cond.alpha.disc.num, e.g. '169.a.169.1'",
    "g2c_curves.class": "isogeny class label: cond.alpha",
    "g2c_curves.cond": "positive integer, conductor",
    "g2c_curves.abs_disc": "absolute value of discriminant",
    "g2c_curves.disc_sign": "+1 or -1",
    "g2c_curves.eqn": "text representation of [f(x), h(x)] defining y^2 + h(x)*y = f(x). Stored as string of nested integer lists, e.g. '[[0,0,0,0,1,1],[1,1,0,1]]'",
    "g2c_curves.igusa_clebsch_inv": "Igusa-Clebsch invariants [I2,I4,I6,I10] as text repr of integer list",
    "g2c_curves.igusa_inv": "Igusa invariants [J2,J4,J6,J8,J10] as text repr",
    "g2c_curves.g2_inv": "G2 invariants [g1,g2,g3] as text repr of rationals",
    "g2c_curves.analytic_rank": "analytic rank of L(J,s)",
    "g2c_curves.mw_rank": "proved Mordell-Weil rank of J(Q), or null",
    "g2c_curves.two_selmer_rank": "rank of 2-Selmer group Sel_2(J/Q)",
    "g2c_curves.torsion_subgroup": "invariant factors of J(Q)_tors as text, e.g. '[2,2]'",
    "g2c_curves.torsion_order": "|J(Q)_tors|",
    "g2c_curves.st_label": "Sato-Tate group label",
    "g2c_curves.st_group": "Sato-Tate group name, e.g. 'USp(4)'",
    "g2c_curves.real_geom_end_alg": "End^0(J) tensor R: 'R', 'C', 'RxR', 'M_2(R)', 'M_2(C)'",
    "g2c_curves.geom_end_alg": "End^0(J_Qbar) tensor Q: 'Q', 'RM', 'CM', 'QxQ', 'M_2(Q)', etc.",
    "g2c_curves.end_alg": "End^0(J) tensor Q: 'Q', 'RM', 'CM', 'QxQ', 'M_2(Q)'",
    "g2c_curves.is_gl2_type": "boolean, Jacobian isogenous to product of elliptic curves",
    "g2c_curves.is_simple_base": "boolean, J is Q-simple",
    "g2c_curves.is_simple_geom": "boolean, J is geometrically simple (over Qbar)",
    "g2c_curves.aut_grp_label": "automorphism group label, e.g. '2.1'",
    "g2c_curves.geom_aut_grp_label": "geometric automorphism group label",
    "g2c_curves.num_rat_pts": "count of rational points on C",
    "g2c_curves.num_rat_wpts": "count of rational Weierstrass points",
    "g2c_curves.has_square_sha": "boolean, Sha is a perfect square",
    "g2c_curves.analytic_sha": "analytic order of Sha from BSD",
    "g2c_curves.locally_solvable": "boolean, C has points in Q_v for all v",
    "g2c_curves.regulator": "height regulator of J(Q)",
    "g2c_curves.real_period": "real period Omega(C/R)",
    "g2c_curves.tamagawa_product": "product of local Tamagawa numbers",
    "g2c_curves.bad_lfactors": "text repr of [[p, [coeffs]], ...]: bad Euler factors as lists of (prime, polynomial coefficients)",
    "g2c_curves.bad_primes": "primes dividing conductor",
    "g2c_curves.root_number": "global root number +1 or -1",

    # ===== g2c_endomorphisms =====
    "g2c_endomorphisms.label": "curve label",
    "g2c_endomorphisms.fod_label": "number field label of field of definition of all endomorphisms",
    "g2c_endomorphisms.fod_coeffs": "defining polynomial coefficients of field of definition",
    "g2c_endomorphisms.factorsQQ_base": "text: factorization of End^0(J) tensor Q as list of [label, poly, disc] triples",
    "g2c_endomorphisms.factorsRR_base": "text: real factors, list of 'R' or 'C' strings",
    "g2c_endomorphisms.factorsQQ_geom": "geometric version of factorsQQ_base",
    "g2c_endomorphisms.factorsRR_geom": "geometric version of factorsRR_base",
    "g2c_endomorphisms.ring_base": "text: [index, is_eichler] for endomorphism ring order",
    "g2c_endomorphisms.ring_geom": "geometric version of ring_base",
    "g2c_endomorphisms.end_lattice": "text: complex nested structure encoding endomorphism data over all intermediate fields",

    "g2c_ratpts.label": "curve label",
    "g2c_ratpts.rat_pts": "text: list of projective rational points [[x,y,z],...]",
    "g2c_ratpts.mw_gens": "text: Mordell-Weil generators as divisor classes",
    "g2c_ratpts.mw_heights": "text: canonical heights of MW generators",
    "g2c_tamagawa.label": "curve label",
    "g2c_tamagawa.p": "bad prime p",
    "g2c_tamagawa.tamagawa_number": "local Tamagawa number c_p",

    # =========================================================================
    # gps_groups — Finite groups
    # =========================================================================
    "gps_groups.label": "group label n.i (order.SmallGroup_index), e.g. '12.4'",
    "gps_groups.order": "group order |G|",
    "gps_groups.exponent": "exponent: minimal m with g^m=1 for all g in G",
    "gps_groups.tex_name": "LaTeX representation, e.g. '$C_4 \\times C_2$'",
    "gps_groups.abelian": "boolean",
    "gps_groups.cyclic": "boolean",
    "gps_groups.nilpotent": "boolean",
    "gps_groups.nilpotency_class": "nilpotency class c: G_{c+1} = 1 in lower central series",
    "gps_groups.solvable": "boolean",
    "gps_groups.supersolvable": "boolean",
    "gps_groups.perfect": "boolean, G = [G,G]",
    "gps_groups.simple": "boolean",
    "gps_groups.almost_simple": "boolean, S <= G <= Aut(S) for simple S",
    "gps_groups.quasisimple": "boolean, perfect central extension of simple group",
    "gps_groups.direct_product": "boolean, G = H x K for nontrivial H,K",
    "gps_groups.semidirect_product": "boolean",
    "gps_groups.wreath_product": "boolean",
    "gps_groups.metabelian": "boolean, [G,G] is abelian",
    "gps_groups.metacyclic": "boolean, has cyclic normal subgroup with cyclic quotient",
    "gps_groups.monomial": "boolean, all irreps are induced from degree 1",
    "gps_groups.rational": "boolean, all character values lie in Q",
    "gps_groups.Agroup": "boolean, all Sylow subgroups are abelian",
    "gps_groups.Zgroup": "boolean, all subgroups are normal",
    "gps_groups.derived_length": "length of derived series",
    "gps_groups.composition_length": "length of composition series",
    "gps_groups.rank": "minimal number of generators",
    "gps_groups.smith_abelian_invariants": "invariant factors of G/[G,G] in Smith normal form, e.g. [2,6] for Z/2 x Z/6",
    "gps_groups.number_conjugacy_classes": "count of conjugacy classes |Cl(G)|",
    "gps_groups.number_subgroups": "total count of subgroups",
    "gps_groups.number_subgroup_classes": "count of conjugacy classes of subgroups",
    "gps_groups.number_normal_subgroups": "count of normal subgroups",
    "gps_groups.number_characteristic_subgroups": "count of characteristic subgroups",
    "gps_groups.center_label": "label of center Z(G)",
    "gps_groups.commutator_label": "label of commutator subgroup [G,G]",
    "gps_groups.abelian_quotient": "label of abelianization G^ab = G/[G,G]",
    "gps_groups.central_quotient": "label of G/Z(G)",
    "gps_groups.frattini_label": "label of Frattini subgroup Phi(G)",
    "gps_groups.aut_order": "|Aut(G)|",
    "gps_groups.outer_order": "|Out(G)| = |Aut(G)/Inn(G)|",
    "gps_groups.transitive_degree": "minimal degree of faithful transitive permutation representation",
    "gps_groups.permutation_degree": "minimal degree of faithful permutation representation",

    # ===== gps subgroups / characters =====
    "gps_subgroups.label": "subgroup relationship label",
    "gps_subgroups.subgroup": "subgroup label (abstract group)",
    "gps_subgroups.ambient": "ambient group label",
    "gps_subgroups.quotient": "quotient group label (if normal)",
    "gps_subgroups.normal": "boolean",
    "gps_subgroups.characteristic": "boolean",
    "gps_subgroups.maximal": "boolean, maximal among proper subgroups",
    "gps_subgroups.central": "boolean, contained in center",
    "gps_subgroups.split": "boolean, extension sequence splits",
    "gps_subgroups.direct": "boolean, direct factor G = H x K",

    # =========================================================================
    # lfunc_lfunctions — L-functions
    # =========================================================================
    "lfunc_lfunctions.label": "L-function label",
    "lfunc_lfunctions.degree": "degree d of the L-function",
    "lfunc_lfunctions.conductor": "conductor N, arbitrary-precision",
    "lfunc_lfunctions.conductor_radical": "radical of conductor (product of distinct prime factors)",
    "lfunc_lfunctions.algebraic": "boolean, true if Dirichlet coefficients are algebraic integers",
    "lfunc_lfunctions.motivic_weight": "motivic weight w",
    "lfunc_lfunctions.self_dual": "boolean",
    "lfunc_lfunctions.primitive": "boolean, true if L-function is primitive",
    "lfunc_lfunctions.central_character": "Dirichlet character label",
    "lfunc_lfunctions.analytic_conductor": "floating-point",
    "lfunc_lfunctions.root_analytic_conductor": "N^(1/d) * product of gamma factors",
    "lfunc_lfunctions.order_of_vanishing": "analytic rank (order of vanishing at center)",
    "lfunc_lfunctions.z1": "imaginary part of lowest nontrivial zero, floating-point",
    "lfunc_lfunctions.positive_zeros_mid": "high-precision zero locations (mantissa), arbitrary-precision array",
    "lfunc_lfunctions.positive_zeros_rad": "error radius for each zero in positive_zeros_mid",
    "lfunc_lfunctions.euler_factors": "JSON list of Euler factor polynomial coefficients at primes 2,3,5,7,... Each = [c0,...,cd] for F_p(T) = c0+c1*T+...+cd*T^d (c0=1). Ints, strings, or [Re,Im] pairs",
    "lfunc_lfunctions.bad_lfactors": "JSON [[p,[c0,...]], ...]: local L-factor at each bad prime. E.g. [[2,[1,-1]]] means F_2(T) = 1-T",
    "lfunc_lfunctions.bad_primes": "list of ramified primes",
    "lfunc_lfunctions.mu_real": "mu parameters (real parts): smallint array of floor(2*mu_j) values",
    "lfunc_lfunctions.mu_imag": "mu parameters (imaginary parts): numeric array",
    "lfunc_lfunctions.nu_real_doubled": "2*nu parameters (real parts): smallint array",
    "lfunc_lfunctions.nu_imag": "nu parameters (imaginary parts): numeric array",
    "lfunc_lfunctions.root_angle_mid": "root number angle theta in [0,1): epsilon = e^(2*pi*i*theta), high-precision",
    "lfunc_lfunctions.root_angle_rad": "error radius for root_angle_mid",
    "lfunc_lfunctions.origin": "URL of source mathematical object",
    "lfunc_lfunctions.instance_types": "list of source object type strings",
    "lfunc_lfunctions.instance_urls": "list of URLs to source mathematical objects",
    "lfunc_lfunctions.spectral_label": "spectral parameter label",
    "lfunc_lfunctions.trace_hash": "hash identifier for fast lookup",

    "lfunc_instances.url": "URL of source mathematical object",
    "lfunc_instances.Lhash": "L-function hash for cross-reference",
    "lfunc_instances.type": "type of source object",

    # =========================================================================
    # belyi_galmaps — Belyi maps (dessins d'enfants)
    # =========================================================================
    "belyi_galmaps.label": "Belyi map label: degTgroup-partitions-orbit, e.g. '6T7-4.2_3.3_4.2-a'",
    "belyi_galmaps.plabel": "passport label",
    "belyi_galmaps.deg": "degree of the Belyi map",
    "belyi_galmaps.g": "genus of the source curve",
    "belyi_galmaps.group": "Galois group label nTt, e.g. '4T5'",
    "belyi_galmaps.group_num": "t-number in nTt notation",
    "belyi_galmaps.geomtype": "'H' = hyperbolic, 'E' = Euclidean, 'S' = spherical",
    "belyi_galmaps.abc": "orders [a,b,c] of ramification above 0,1,infinity",
    "belyi_galmaps.base_field": "polredabs polynomial coefficients of field of definition",
    "belyi_galmaps.base_field_label": "LMFDB number field label of field of definition",
    "belyi_galmaps.moduli_field": "polredabs polynomial coefficients of field of moduli",
    "belyi_galmaps.moduli_field_label": "LMFDB number field label of field of moduli",
    "belyi_galmaps.embeddings": "JSON: complex embeddings of base_field as list of [real, imag] pairs",
    "belyi_galmaps.triples": "JSON: permutation triples per embedding. Each triple = 3 permutations as lists",
    "belyi_galmaps.triples_cyc": "JSON: same triples in cycle notation, e.g. [[[1,4,3,6],[2,5,8,7]],...]",
    "belyi_galmaps.orbit_size": "size of Galois orbit of this dessin",
    "belyi_galmaps.pass_size": "number of dessins in the passport",
    "belyi_galmaps.aut_group": "JSON: automorphism group generators in one-line permutation notation",
    "belyi_galmaps.lambdas": "JSON: conjugacy type of each triple as partitions, e.g. [[4,2],[3,3],[4,2]]",
    "belyi_galmaps.models": "JSON list of model dicts: {model_type, ..., curve, map} with equation data",
    "belyi_galmaps.a_s": "smallest element of abc",
    "belyi_galmaps.b_s": "second smallest element of abc",
    "belyi_galmaps.c_s": "largest element of abc",
    "belyi_galmaps.curve_label": "LMFDB label of the source curve (if it exists in LMFDB)",
    "belyi_galmaps.friends": "list of URLs to related LMFDB objects",
    "belyi_galmaps.specializations": "JSON: map t -> specialization data",

    "belyi_passports.plabel": "passport label",
    "belyi_passports.group": "group label nTt",
    "belyi_passports.abc": "orders [a,b,c]",
    "belyi_passports.g": "genus",
    "belyi_passports.deg": "degree",
    "belyi_passports.pass_size": "number of Belyi maps in passport",
    "belyi_passports.num_orbits": "number of Galois orbits in passport",
    "belyi_passports.a_s": "smallest element of abc",
    "belyi_passports.b_s": "second smallest element",
    "belyi_passports.c_s": "largest element",
    "belyi_passports.maxdegbf": "maximal degree of base field among maps in passport",
    "belyi_passports.lambdas": "JSON list of 3 partitions: cycle structures of (sigma_0, sigma_1, sigma_inf). Each = descending list of positive ints summing to degree",
    "belyi_passports.geomtype": "'H', 'E', or 'S'",

    # =========================================================================
    # artin_reps — Artin representations
    # =========================================================================
    "artin_reps.label": "Artin representation label",
    "artin_reps.Baselabel": "base representation label (without GaloisConjugate suffix)",
    "artin_reps.Dim": "dimension of the representation",
    "artin_reps.Conductor": "Artin conductor",
    "artin_reps.NFGal": "number field polynomial (defining the Galois closure)",
    "artin_reps.Is_Even": "boolean, true if det(rho) is even (trivial on complex conjugation)",
    "artin_reps.BadPrimes": "ramified primes",
    "artin_reps.HardPrimes": "primes where local computation is difficult",
    "artin_reps.Container": "smallest permutation container nTt",
    "artin_reps.Proj_nTj": "projective image in nTt notation",
    "artin_reps.GalConjSigns": "signs for each Galois conjugate representation",
    "artin_reps.Dets": "determinants of conjugate representations (character labels)",
    "artin_reps.GaloisConjugates": "JSON: array of conjugate representations with local factors",
    "artin_reps.LocalFactors": "local L-factor data at primes",

    "artin_field_data.Polynomial": "defining polynomial of number field",
    "artin_field_data.Size": "Galois group order |Gal(K/Q)|",
    "artin_field_data.TransitiveDegree": "degree of the number field [K:Q]",
    "artin_field_data.ArtinReps": "JSON: list of Artin representations arising from this field",
    "artin_field_data.Frobs": "JSON: Frobenius conjugacy classes indexed by prime",
    "artin_field_data.ConjClasses": "JSON: conjugacy class data (sizes, orders, representatives)",
    "artin_field_data.FrobResolvents": "JSON: Frobenius resolvent data",
    "artin_field_data.G-Gens": "Galois group generators (permutations)",
    "artin_field_data.G-Name": "Galois group name string",
    "artin_field_data.QpRts": "p-adic roots of defining polynomial",
    "artin_field_data.QpRts-minpoly": "minimal polynomial for p-adic root computation",
    "artin_field_data.QpRts-p": "prime p used for p-adic roots",
    "artin_field_data.QpRts-prec": "precision of p-adic root computation",
    "artin_field_data.ComplexConjugation": "index of conjugacy class of complex conjugation",

    # =========================================================================
    # lf_fields — Local fields (p-adic fields)
    # =========================================================================
    "lf_fields.label": "p-adic field label, e.g. '2.4.6.7'",
    "lf_fields.p": "prime p (residue characteristic)",
    "lf_fields.n": "degree [K:Q_p]",
    "lf_fields.e": "ramification index e(K/Q_p)",
    "lf_fields.f": "residue degree f(K/Q_p), so n = e*f",
    "lf_fields.c": "discriminant exponent v_p(disc(K/Q_p))",
    "lf_fields.gal": "Galois group label of Galois closure",
    "lf_fields.top_slope": "highest slope in ramification polygon (as rational string)",
    "lf_fields.slopes": "all ramification filtration slopes (as list of rational strings)",

    # =========================================================================
    # hgm — Hypergeometric motives
    # =========================================================================
    "hgm_families.A": "list of alpha parameters (cyclotomic orders defining the hypergeometric datum)",
    "hgm_families.B": "list of beta parameters (cyclotomic orders)",
    "hgm_families.Arev": "reversed/complementary alpha parameters",
    "hgm_families.Brev": "reversed/complementary beta parameters",
    "hgm_families.A2": "2-part of A after prime cancellation",
    "hgm_families.A2rev": "2-part of B after cancellation",
    "hgm_families.A3": "3-part of A",
    "hgm_families.A3rev": "3-part of B",
    "hgm_families.A5": "5-part of A",
    "hgm_families.A5rev": "5-part of B",
    "hgm_families.A7": "7-part of A",
    "hgm_families.A7rev": "7-part of B",
    "hgm_families.Au2": "prime-to-2-part of A",
    "hgm_families.Au2rev": "prime-to-2-part of B",
    "hgm_families.Au3": "prime-to-3-part of A",
    "hgm_families.Au3rev": "prime-to-3-part of B",
    "hgm_families.Au5": "prime-to-5-part of A",
    "hgm_families.Au5rev": "prime-to-5-part of B",
    "hgm_families.Au7": "prime-to-7-part of A",
    "hgm_families.Au7rev": "prime-to-7-part of B",
    "hgm_families.famhodge": "Hodge vector of the hypergeometric family",
    "hgm_families.hodge": "Hodge numbers",
    "hgm_families.label": "family label",
    "hgm_families.degree": "degree of the motive",
    "hgm_families.weight": "motivic weight",
    "hgm_families.gal2": "mod-2 Galois/monodromy data",
    "hgm_families.gal3": "mod-3 Galois/monodromy data",
    "hgm_families.gal5": "mod-5 Galois/monodromy data",
    "hgm_families.gal7": "mod-7 Galois/monodromy data",

    "hgm_motives.label": "motive label (specialization of a family at parameter t)",
    "hgm_motives.A": "alpha parameters",
    "hgm_motives.B": "beta parameters",
    "hgm_motives.Arev": "reversed alpha",
    "hgm_motives.Brev": "reversed beta",
    "hgm_motives.famhodge": "Hodge vector of parent family",
    "hgm_motives.hodge": "Hodge numbers of the specialization",
    "hgm_motives.locinfo": "local L-factor data at bad primes (JSON)",
    "hgm_motives.centralval": "central L-value (real number)",
    "hgm_motives.euler_factors": "Euler factors at good primes (JSON list of polynomial coefficient lists)",
    "hgm_motives.wild_primes": "wildly ramified primes",
    "hgm_motives.t": "specialization parameter t (rational as [num, den])",
    "hgm_motives.conductor": "conductor, arbitrary-precision integer",
    "hgm_motives.sign": "root number +1 or -1",
    "hgm_motives.family": "parent family label",
    "hgm_motives.degree": "degree of the motive",
    "hgm_motives.weight": "motivic weight",
    "hgm_motives.Lhash": "L-function hash for cross-reference",
    "hgm_motives.root_analytic_conductor": "floating-point approximation",
    "hgm_motives.gal2": "mod-2 monodromy data",
    "hgm_motives.gal3": "mod-3 monodromy data",
    "hgm_motives.gal5": "mod-5 monodromy data",
    "hgm_motives.gal7": "mod-7 monodromy data",

    "hgm_euler_survey.label": "motive label",
    "hgm_euler_survey.p": "prime",
    "hgm_euler_survey.eulers": "Euler factor data at prime p",
    "hgm_euler_survey.eulers_factored": "factored Euler factor data",

    # =========================================================================
    # hmf — Hilbert modular forms
    # =========================================================================
    "hmf_forms.label": "HMF label: field_label-level_label-label_suffix",
    "hmf_forms.field_label": "base totally real number field label",
    "hmf_forms.deg": "degree [F:Q] of base field",
    "hmf_forms.disc": "discriminant of base field",
    "hmf_forms.level_label": "level ideal label",
    "hmf_forms.level_norm": "norm of level ideal",
    "hmf_forms.weight": "weight vector [k1,...,kd] (one weight per real embedding)",
    "hmf_forms.parallel_weight": "common weight k if all weights equal (parallel weight)",
    "hmf_forms.dimension": "dimension of the eigenspace",
    "hmf_forms.is_CM": "boolean, has complex multiplication",
    "hmf_forms.is_base_change": "boolean, arises as base change from Q or smaller field",

    # =========================================================================
    # av_fq — Abelian varieties over finite fields
    # =========================================================================
    "av_fq_isog.label": "isogeny class label, e.g. '2.16.am_cn'",
    "av_fq_isog.g": "dimension (genus) of the abelian variety",
    "av_fq_isog.q": "finite field cardinality q = p^a",
    "av_fq_isog.p": "characteristic p",
    "av_fq_isog.p_rank": "p-rank (0 to g)",
    "av_fq_isog.angle_rank": "number of non-real roots of Weil polynomial divided by 2",
    "av_fq_isog.polynomial": "Weil polynomial (char poly of Frobenius) as text",
    "av_fq_isog.is_simple": "boolean, simple over F_q",
    "av_fq_isog.is_primitive": "boolean, not isogenous to base change from smaller field",
    "av_fq_isog.is_geometrically_simple": "boolean, simple over algebraic closure",

    # =========================================================================
    # bmf — Bianchi modular forms
    # =========================================================================
    "bmf_forms.label": "BMF label: field_label-level_label-suffix",
    "bmf_forms.field_label": "imaginary quadratic field label (2.0.D.1)",
    "bmf_forms.level_label": "level ideal label",
    "bmf_forms.level_norm": "norm of level ideal",
    "bmf_forms.weight": "integer weight (parallel weight 2 for all currently stored)",
    "bmf_forms.dimension": "dimension of eigenspace (1 for rational newforms)",
    "bmf_forms.sfe": "sign of functional equation: +1, -1, or '?' (unknown)",
    "bmf_forms.CM": "CM discriminant, 0 if no CM, or '?' if unknown",
    "bmf_forms.bc": "base change status: 0=no, +/-1=yes from Q, +/-n=twist of base change",

    # ===== modcurve =====
    "modcurve_curves.label": "modular curve label, e.g. '13.78.3.a.1'",
    "modcurve_curves.level": "level N",
    "modcurve_curves.index": "index [PSL(2,Z) : H] of the defining subgroup",
    "modcurve_curves.genus": "geometric genus of the curve",
    "modcurve_curves.rank": "rank of the Jacobian J(Q)",
    "modcurve_curves.cusps": "total number of cusps",
    "modcurve_curves.rational_cusps": "number of cusps defined over Q",
    "modcurve_curves.q_gonality": "Q-gonality (min degree of non-constant map to P^1 over Q)",
    "modcurve_curves.nu2": "number of elliptic points of order 2",
    "modcurve_curves.nu3": "number of elliptic points of order 3",
    "modcurve_curves.contains_negative_one": "boolean, true if -I is in the subgroup H",

    # ===== lat =====
    "lat_lattices.label": "lattice label: dim.det.level.class.number",
    "lat_lattices.dim": "dimension of the lattice",
    "lat_lattices.det": "determinant of the Gram matrix",
    "lat_lattices.level": "level of the lattice (= det/gcd for certain normalizations)",
    "lat_lattices.name": "common name if known, e.g. 'E8', 'Leech'",
    "lat_lattices.gram": "Gram matrix as upper-triangular integer list (row-major upper triangle)",
    "lat_lattices.minimum": "minimal nonzero norm in the lattice",
    "lat_lattices.aut": "order of automorphism group |Aut(L)|",
    "lat_lattices.kissing_number": "number of vectors achieving the minimum norm",
    "lat_lattices.theta_series": "coefficients of theta function sum_{v in L} q^{v.v}",

    # ===== smf =====
    "smf_newforms.label": "Siegel modular form label",
    "smf_newforms.degree": "degree of the Siegel modular form (e.g. 2 for Sp(4))",
    "smf_newforms.weight": "weight k",
    "smf_newforms.level": "level N",
    "smf_newforms.dim": "dimension of eigenspace",

    # ===== char =====
    "char_dir_orbits.modulus": "integer modulus N of (Z/NZ)*",
    "char_dir_orbits.orbit_index": "1-indexed ordinal of Galois orbit",
    "char_dir_orbits.conductor": "conductor of the character",
    "char_dir_orbits.order": "multiplicative order of the character",
    "char_dir_orbits.is_primitive": "boolean",
    "char_dir_orbits.is_real": "boolean, character is real-valued",
    "char_dir_orbits.is_minimal": "boolean, minimal conductor in twist class",
    "char_dir_orbits.degree": "degree [Q(chi):Q] of the value field",
    "char_dir_orbits.parity": "1 = even, -1 = odd",

    # ===== maass =====
    "maass_rigor.maass_label": "Maass form label: level.weight.conrey.spectral_index",
    "maass_rigor.level": "positive integer level",
    "maass_rigor.weight": "integer weight (currently always 0)",
    "maass_rigor.spectral_parameter": "eigenvalue R of Laplacian: lambda = 1/4 + R^2. High-precision real",
    "maass_rigor.symmetry": "0 = even, 1 = odd",
    "maass_rigor.fricke_eigenvalue": "+1 or -1 (or 0 if unknown)",
    "maass_rigor.coefficients": "Fourier coefficients a_n as list of real numbers",

    # ===== hgcwa =====
    "hgcwa_passports.label": "family label: genus.g0.signature_str.group_label",
    "hgcwa_passports.genus": "genus g of the curve",
    "hgcwa_passports.g0": "genus of the quotient curve C/G",
    "hgcwa_passports.dim": "dimension of the family (moduli space)",
    "hgcwa_passports.group_order": "order of the automorphism group",
    "hgcwa_passports.hyperelliptic": "boolean, family contains hyperelliptic curves",
    "hgcwa_passports.cyclic_trigonal": "boolean, family contains cyclic trigonal curves",

    # ===== modlgal =====
    "modlgal_reps.label": "representation label: dim.ell.conductor.order[.twist]",
    "modlgal_reps.base_ring_characteristic": "prime ell",
    "modlgal_reps.dimension": "dimension of the representation over F_ell",
    "modlgal_reps.conductor": "Artin conductor",
    "modlgal_reps.image_label": "label of the image group",
    "modlgal_reps.image_order": "|im(rho)|",
    "modlgal_reps.is_surjective": "boolean",
    "modlgal_reps.is_absolutely_irreducible": "boolean",
    "modlgal_reps.kernel_polynomial": "polynomial defining the kernel (fixed) field",

    # ===== modlgal_reps_save (old table) =====
    "modlgal_reps_save.bad_prime_list": "JSON list of [prime, field1, field2, field3, field4] tuples for bad primes (primes dividing ell*conductor), with Frobenius data",
    "modlgal_reps_save.good_prime_list": "JSON list of [prime, trace_vector, factored_charpoly_string, image_order, image_index] tuples for unramified primes p < 100",

    # ===== hecke algebras =====
    "hecke_algebras.label": "Hecke algebra label",
    "hecke_algebras.level": "positive integer level",
    "hecke_algebras.weight": "positive integer weight",
    "hecke_algebras.num_orbits": "number of Hecke orbits",
    "hecke_ladic.field": "JSON [index, degree, poly_string, index2]: l-adic coefficient field. field[1]=degree, field[2]=defining polynomial as string",
    "hecke_ladic.operators": "JSON list of Hecke operators T_p mod l. Each entry = flat list of dim^2 integers (row-major matrix over Z/lZ)",
    "hecke_ladic.properties": "JSON [grading_list, gorenstein_defect]: grading_list = list of ints, gorenstein_defect = int (0 means Gorenstein)",
    "hecke_ladic.structure": "JSON [dim, num_gens, gens_sage_str, rels_sage_str]: dimension, number of generators, SageMath-evaluable strings for generators and relations",
    "hecke_orbits.Qalg_gen": "JSON list of integers: indices of Hecke operators T_n generating the Hecke algebra over Q",
    "hecke_orbits.Qbasis": "JSON list of integers: indices for a Q-basis of the Hecke algebra as a Q-vector space",
    "hecke_orbits.Zbasis": "JSON list of flattened square matrices (each inner list has dim^2 entries as strings): Z-basis elements for the Hecke order, each stored row-major",
    "hecke_orbits.disc_fac": "JSON list of [prime, exponent] pairs (as strings): prime factorization of the discriminant of the Hecke Z-order",

    # ===== belyi (additional) =====
    "belyi_passports.aut_group": "JSON list of permutations in one-line notation: generators of Aut(phi), the automorphism group of the Belyi map. E.g. [[3,4,1,2],[4,3,2,1]]",
    "belyi_passports.embeddings": "JSON list of [Re, Im] pairs (floats): complex embeddings of the base field generator, one per Galois conjugate",
    "belyi_passports.lambdas": "JSON list of exactly 3 partitions: cycle structures of (sigma_0, sigma_1, sigma_inf). Each partition = descending list of positive ints summing to degree d",
    "belyi_passports.models": "JSON list of model dicts {model_type, curve, map, ...}: alternative geometric models for the Belyi curve and map (or null)",
    "belyi_passports.specializations": "JSON (not yet populated): intended for specializations of the Belyi map at specific parameter values",
    "belyi_passports.triples": "JSON list of monodromy triples: each = [[perm0],[perm1],[perm_inf]] in one-line notation (lists of d ints). One triple per Galois conjugate. sigma_0*sigma_1*sigma_inf = id",
    "belyi_passports.triples_cyc": "JSON list of monodromy triples in cycle notation: each = ['cycle_str0','cycle_str1','cycle_str_inf']. E.g. [['(1,4,3)(2,5)','(1,2,3)','(1,5,4,2,3)']]",

    # ===== bmf (additional) =====
    "bmf_forms.AL_eigs": "JSON list of Atkin-Lehner eigenvalues (+1 or -1, or string '?' if unknown), one per prime dividing the level",
    "bmf_forms.hecke_eigs": "JSON list of Hecke eigenvalues a_P for primes P ordered by norm. Integers for rational forms; polynomial strings in Hecke field generator for higher-dimensional forms. '?' if unknown",

    # ===== hmf (additional) =====
    "hmf_forms_temp.hecke_field": "JSON (unpopulated staging column, table has 0 rows): intended to store Hecke eigenvalue field polynomial",

    # ===== lfunc (additional) =====
    "lfunc_lfunctions.euler_factors": "JSON list of Euler factor polynomial coefficients at successive primes (2,3,5,7,...). Each entry = [c0,c1,...,cd] for F_p(T) = c0 + c1*T + ... + cd*T^d. c0=1 always. Coefficients are ints, or strings like 'a^k' for algebraic L-functions, or [Re,Im] pairs for CDF",
    "lfunc_lfunctions.bad_lfactors": "JSON list of [prime, [c0,...,cd]] pairs: local L-factor polynomial at each bad prime. E.g. [[3011,[1]]] means F_3011(T)=1 (fully ramified). Same coefficient conventions as euler_factors",
    "lfunc_lfunctions.euler_factors_factorization": "JSON list (indexed by prime) of factorizations. Each = list of [factor_coeffs, exponent] pairs. factor_coeffs = [c0,...] for an irreducible factor, exponent = multiplicity",
    "lfunc_lfunctions.plot_values": "JSON list of floats: values of the Hardy Z-function Z(k*plot_delta) for k=0,1,2,... Used to draw the L-function plot on the critical line",

    # ===== gps_qrep =====
    "gps_qrep.clases": "JSON list of conjugacy class data [[order, size, index],...] for the finite subgroup of GL(n,Q)",
    "gps_qrep.maximal_subgroups": "JSON list of labels/data for maximal subgroups of the group",
    "gps_qrep.normal_subgroups": "JSON list of labels/data for normal subgroups of the group",

    # ===== lf (additional) =====
    "lf_fields.inertia": "JSON ['t', [n, t]] for transitive inertia group nTt, or ['i', [order, gap_id]] for intransitive. E.g. ['t', [6, 6]] means inertia subgroup is 6T6",
    "lf_galois.inertia": "JSON ['t', [n, t]] for transitive inertia group nTt, or ['i', [order, gap_id]] for intransitive",
    "lf_tori.inertia": "JSON ['t', [n, t]] for transitive inertia group nTt, or ['i', [order, gap_id]] for intransitive",

    # ===== modcurve (additional) =====
    "modcurve_points.coordinates": "JSON dict: keys are model type ints (as strings, 0=canonical, 2=plane, 5=Weierstrass), values are lists of coordinate strings in the residue field basis",
    "modcurve_points_old.coordinates": "JSON dict: keys are model type ints (as strings), values are lists of coordinate strings in the residue field basis",

    # ===== av (additional) =====
    "av_fq_isog.twists": "JSON list of [twist_label, base_change_label, min_extension_degree] triples: each identifies a twist, its common base change, and the minimal degree extension where the two become isogenous",
    "av_fq_pol.representative": "JSON [denominator, [c0,c1,...]]: representative ideal for weak equivalence class of polarization. Ideal = (c0*w0 + c1*w1 + ...)/denominator in endomorphism ring Z-basis",

    # ===== hgcwa (additional) =====
    "hgcwa_passports.jacobian_decomp": "JSON list of [dim, multiplicity, char_index] triples: Jacobian decomposes as product of A_dim^mult for each character. E.g. [3,1,2] means one copy of a 3-dimensional abelian variety from character #2",

    # ===== weil =====
    "weil_basechange.twists": "JSON list of [twist_label, base_change_label, extension_degree] triples (same format as av_fq_isog.twists)",

    # ===== Test/staging table duplicates (same schema as main tables) =====
    "ec_nfcurves_test.bad_primes": "JSON list of prime ideal strings in w-generator notation (same as ec_nfcurves)",
    "ec_nfcurves_test.base_change": "JSON list of curve labels this is a base change of (same as ec_nfcurves)",
    "ec_nfcurves_test.galois_images": "JSON list of Sutherland GL2(F_p) subgroup labels (same as ec_nfcurves)",
    "ec_nfcurves_test.gens": "JSON list of MW generator strings as projective points over K (same as ec_nfcurves)",
    "ec_nfcurves_test.isogeny_matrix": "JSON nested list of isogeny degrees (same as ec_nfcurves)",
    "ec_nfcurves_test.local_data": "JSON list of dicts per bad prime (same as ec_nfcurves)",
    "ec_nfcurves_test.non_min_p": "JSON list of prime ideal strings where model is not minimal (same as ec_nfcurves)",
    "ec_nfcurves_test.rank_bounds": "JSON [lower, upper] bounds for rank (same as ec_nfcurves)",
    "ec_nfcurves_test.signature": "JSON [r1, r2] signature of base field K (same as ec_nfcurves)",
    "ec_nfcurves_test.torsion_gens": "JSON list of torsion generator strings as projective points (same as ec_nfcurves)",
    "ec_nfcurves_test.torsion_structure": "JSON list of invariant factors of E(K)_tors (same as ec_nfcurves)",
    "belyi_galmaps_test.aut_group": "JSON list of permutations in one-line notation: generators of Aut(phi) (same as belyi_passports)",
    "belyi_galmaps_test.embeddings": "JSON list of [Re, Im] pairs: complex embeddings (same as belyi_passports)",
    "belyi_galmaps_test.lambdas": "JSON list of 3 partitions: ramification type (same as belyi_passports)",
    "belyi_galmaps_test.models": "JSON list of model dicts (same as belyi_passports)",
    "belyi_galmaps_test.specializations": "JSON (not yet populated, same as belyi_passports)",
    "belyi_galmaps_test.triples": "JSON list of monodromy triples in one-line notation (same as belyi_passports)",
    "belyi_galmaps_test.triples_cyc": "JSON list of monodromy triples in cycle notation (same as belyi_passports)",
    "bmf_test.AL_eigs": "JSON list of Atkin-Lehner eigenvalues (same as bmf_forms)",
    "bmf_test.hecke_eigs": "JSON list of Hecke eigenvalues a_P (same as bmf_forms)",
    "gps_small.clases": "JSON list of conjugacy class data [[order, size, index],...] (same as gps_qrep)",
    "gps_small.maximal_subgroups": "JSON list of labels/data for maximal subgroups (same as gps_qrep)",
    "gps_small.normal_subgroups": "JSON list of labels/data for normal subgroups (same as gps_qrep)",
    "hgcwa_genvectors.jacobian_decomp": "JSON list of [dim, mult, char_index] triples: Jacobian decomposition (same as hgcwa_passports)",
    "lfunc_data.bad_lfactors": "JSON [[p,[c0,...]],...]: local L-factor at each bad prime (same as lfunc_lfunctions)",
    "lfunc_data.euler_factors": "JSON list of Euler factor polynomial coefficients at primes (same as lfunc_lfunctions)",
    "lfunc_data.euler_factors_factorization": "JSON list of Euler factor factorizations (same as lfunc_lfunctions)",
    "lfunc_data.plot_values": "list of floats: values of Hardy Z-function Z(k*plot_delta) (same as lfunc_lfunctions)",

    # ===== data (metadata tables) =====
    "data_submissions.processed": "timestamp (datetime) when processing finished",
    "data_submissions.reviewed": "timestamp (datetime) when reviewed",
    "data_submissions.submitted": "timestamp (datetime) initially submitted",
    "data_submissions.updated": "timestamp (datetime) of most recent change",
    "data_submissions.verified": "timestamp (datetime) when verification finished",
    "data_uploads.processed": "timestamp (datetime) when processing finished",
    "data_uploads.reviewed": "timestamp (datetime) when reviewed",
    "data_uploads.submitted": "timestamp (datetime) initially submitted",
    "data_uploads.updated": "timestamp (datetime) of most recent change",
    "data_uploads.verified": "timestamp (datetime) when verification finished",

    # ===== inv (inventory tables — internal metadata) =====
    "inv_tables.data": "JSON object: inventory data for the table (internal metadata)",
    "inv_tables.INFO": "JSON object: aggregated inventory info (internal metadata)",
    "inv_tables.NOTES": "JSON object: aggregated inventory notes (internal metadata)",
    "inv_tables.scan_date": "timestamp (datetime) of last scan",
    "inv_fields.data": "JSON object: inventory data for the field (internal metadata)",
    "inv_fields_auto.data": "JSON object: auto-generated inventory data for the field (internal metadata)",
    "inv_fields_human.data": "JSON object: human-curated inventory data for the field (internal metadata)",
    "inv_livedata.content": "JSON object: live database content snapshot (internal)",
    "inv_livedata.scan_date": "timestamp (datetime) of last scan",
    "inv_ops.content": "JSON object: inventory operation content (internal metadata)",
    "inv_ops.scan_date": "timestamp (datetime) of last scan",
    "inv_diffs.diff": "JSON: diff between expected and actual database content (internal)",
    "inv_rollback.diff": "JSON: diff for rollback operation (internal metadata)",
    "inv_all.INFO": "JSON object: aggregated inventory info (internal)",
    "inv_all.NOTES": "JSON object: aggregated inventory notes (internal)",
    "inv_all.scan_date": "timestamp (datetime) of last scan",
}
# fmt: on
